### ISSUE TITLE
save_bar_data 更新后，数据库会丢失bar start 当月开始至 bar start 之间的数据

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy_arctic#14]
save_bar_data函数中数据更新
self.bar_library.update(table_name, df, upsert=True, chunk_size="M") 
可以看出以 Month为单位保存的

直接将 bar的df更新，会导致第一个月的月初至bar start之间好几天的数据丢失

**Comment by Edanflame** [comment]
你好，这个问题在之前版本中已修复，可以尝试更新试试。

**Comment by yhmickey** [comment]
更新后，问题已解决，谢谢~
