### ISSUE TITLE
load_tick_data 报错

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy_arctic#15]
版本：  vnpy 2.9.0
             vnpy-arctic 1.0.2

使用data_recorder模块记录了几天tick数据，读取时报错如下（bar数据读取没有错误）：

---------------------------------------------------------------------------
ServerSelectionTimeoutError               Traceback (most recent call last)
~\AppData\Local\Temp\2\ipykernel_8932\1430917318.py in <module>
----> 1 tick = database.load_tick_data('BTCUSDT',Exchange.BINANCE,start,end)

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\vnpy_arctic\arctic_database.py in load_tick_data(self, symbol, exchange, start, end)
    213         table_name = generate_table_name(symbol, exchange)
    214         df = self.tick_library.read(
--> 215             table_name, chunk_range=DateRange(start, end))
    216 
    217         if df.empty:

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\arctic\chunkstore\chunkstore.py in read(self, symbol, chunk_range, filter_data, **kwargs)
    252             symbol = [symbol]
    253 
--> 254         sym = self._get_symbol_info(symbol)
    255         if not sym:
    256             raise NoDataFoundException('No data found for %s' % (symbol))

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\arctic\chunkstore\chunkstore.py in _get_symbol_info(self, symbol)
    188     def _get_symbol_info(self, symbol):
    189         if isinstance(symbol, list):
--> 190             return list(self._symbols.find({SYMBOL: {'$in': symbol}}))
    191         return self._symbols.find_one({SYMBOL: symbol})
    192 

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\pymongo\cursor.py in next(self)
   1236         if self.__empty:
   1237             raise StopIteration
-> 1238         if len(self.__data) or self._refresh():
   1239             if self.__manipulate:
   1240                 _db = self.__collection.database

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\pymongo\cursor.py in _refresh(self)
   1128 
   1129         if not self.__session:
-> 1130             self.__session = self.__collection.database.client._ensure_session()
   1131 
   1132         if self.__id is None:  # Query

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\pymongo\mongo_client.py in _ensure_session(self, session)
   1933             # Don't make implicit sessions causally consistent. Applications
   1934             # should always opt-in.
-> 1935             return self.__start_session(True, causal_consistency=False)
   1936         except (ConfigurationError, InvalidOperation):
   1937             # Sessions not supported, or multiple users authenticated.

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\pymongo\mongo_client.py in __start_session(self, implicit, **kwargs)
   1881 
   1882         # Raises ConfigurationError if sessions are not supported.
-> 1883         server_session = self._get_server_session()
   1884         opts = client_session.SessionOptions(**kwargs)
   1885         return client_session.ClientSession(

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\pymongo\mongo_client.py in _get_server_session(self)
   1919     def _get_server_session(self):
   1920         """Internal: start or resume a _ServerSession."""
-> 1921         return self._topology.get_server_session()
   1922 
   1923     def _return_server_session(self, server_session, lock):

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\pymongo\topology.py in get_server_session(self)
    518             # Sessions are always supported in load balanced mode.
    519             if not self._settings.load_balanced:
--> 520                 session_timeout = self._check_session_support()
    521             else:
    522                 # Sessions never time out in load balanced mode.

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\pymongo\topology.py in _check_session_support(self)
    500                         any_server_selector,
    501                         self._settings.server_selection_timeout,
--> 502                         None)
    503             elif not self._description.readable_servers:
    504                 self._select_servers_loop(

C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\pymongo\topology.py in _select_servers_loop(self, selector, timeout, address)
    218                 raise ServerSelectionTimeoutError(
    219                     "%s, Timeout: %ss, Topology Description: %r" %
--> 220                     (self._error_message(selector), timeout, self.description))
    221 
    222             self._ensure_opened()

ServerSelectionTimeoutError: localhost:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。, Timeout: 30.0s, Topology Description: <TopologyDescription id: 6210b1dcf70c29909bba046a, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')>]>

**Comment by Edanflame** [comment]
无法连接是因为mongodb数据库关闭了吧，可以检查一下mongodb是否还在运行
