### ISSUE TITLE
每次调用数据库时，总是报Library created, but couldn't enable sharding，如何能够不显示

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy_arctic#17]
如何能够不显示如下信息。每次调用时都出来。

Library created, but couldn't enable sharding: no such command: 'enablesharding', full error: {'ok': 0.0, 'errmsg': "no such command: 'enablesharding'", 'code': 59, 'codeName': 'CommandNotFound'}. This is OK if you're not 'admin'

**Comment by Edanflame** [comment]
这个是调用arctic产生的，目前好像没有办法消除
