### ISSUE TITLE
arctic认证问题

### ISSUE THREAD

**Issue by ZzzzHeJ** [vnpy/vnpy_arctic#7]
1.01代码中无法对arctic进行认证，建议将arctic_database中27-33行https://github.com/vnpy/vnpy_arctic/blob/e4c5bc9de7eaabfee0e9bf410f0604259919e6fd/vnpy_arctic/arctic_database.py#L28
更新为以下代码

`        self.connection: Arctic = Arctic(
            SETTINGS["database.host"],
            tz_aware=True,
            tzinfo=DB_TZ,
            username=SETTINGS["database.user"],
            password=SETTINGS["database.password"],
        )`

**Comment by Edanflame** [comment]
已在https://github.com/vnpy/vnpy_arctic/pull/12中添加

**Comment by Edanflame** [comment]
已在https://github.com/vnpy/vnpy_arctic/pull/12 中添加
