### ISSUE TITLE
数据库的创建问题

### ISSUE THREAD

**Issue by ZzzzHeJ** [vnpy/vnpy_arctic#8]
对于未使用arctic的用户来说，已有的代码能够方便的进行数据存储，但是对于之前经常使用arctic的用户，则容易导致新加载数据与已有数据混在一起，不方便管理。
https://github.com/vnpy/vnpy_arctic/blob/e4c5bc9de7eaabfee0e9bf410f0604259919e6fd/vnpy_arctic/arctic_database.py#L33
建议增加一个appname，能够将数据存入指定的独立集合中

`        self.connection.initialize_library(f"{appname}.bar_data", CHUNK_STORE)
        self.connection.initialize_library(f"{appname}.tick_data", CHUNK_STORE)
        self.connection.initialize_library(f"{appname}.data_overview", METADATA_STORE)

        self.bar_library: ChunkStore = self.connection[f"{appname}.bar_data"]
        self.tick_library: ChunkStore = self.connection[f"{appname}.tick_data"]
        self.overview_library: MetadataStore = self.connection[f"{appname}.data_overview"]
`

**Comment by noranhe** [comment]
已修复
